/**
 * C2PA / Content Credentials examples
 *
 * Content Credentials tell you whether an image declares itself as AI
 * generated. rokka reads them automatically on every upload.
 */

import { Rokka } from '../src'
import { StaticMetadata } from '../src/apis/sourceimages'

const client = new Rokka({
  apiKey: 'your-api-key',
})

const hash = 'c421f4e8cefe0fd3aab22832f51e85bacda0a47a'

// Example: Read the content credentials of an already uploaded image
//
// Sourceimage.static_metadata is untyped, cast it to StaticMetadata to get
// the typing for the content_credentials block.
async function readContentCredentials() {
  const response = await client.sourceimages.get('myorg', hash)
  const staticMetadata = response.body.static_metadata as
    | StaticMetadata
    | undefined
  const credentials = staticMetadata?.content_credentials

  // the whole block is missing when the image has no readable manifest,
  // which is different from a block with present: false
  if (!credentials) {
    console.log('No readable C2PA manifest')
    return
  }
  if (credentials.ai_generated) {
    console.log('AI generated by', credentials.generator)
    console.log('Signed by', credentials.signed_by)
  }
}

// Example: Re-read the content credentials from the original file
//
// The response of this one is already typed, no cast needed.
async function refreshContentCredentials() {
  const response = await client.sourceimages.contentCredentials('myorg', hash)
  const credentials = response.body.static_metadata?.content_credentials
  console.log('Validation state:', credentials?.validation_state)
}

// Example: Search for AI generated images
//
// Search values always have to be strings, 'true' and not true.
async function searchAiGeneratedImages() {
  const response = await client.sourceimages.list('myorg', {
    search: {
      'static:boolean:content_credentials__ai_generated': 'true',
    },
  })
  console.log(`${response.body.total} AI generated images`)
}

// Example: Search for images generated by a specific generator
async function searchByGenerator() {
  const response = await client.sourceimages.list('myorg', {
    search: {
      'static:text:content_credentials__generator': 'gpt-image',
    },
  })
  for (const image of response.body.items) {
    console.log(image.hash, image.name)
  }
}
